package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.ICharacterRepository;
import dao.uow.IUnitOfWork;
import domain.model.Character;

public class CharacterRepository extends RepositoryBase<Character> implements ICharacterRepository {

	public CharacterRepository(Connection connection, IMapResultSetIntoEntity<Character> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE character(" + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "faction varchar(10)," + "race varchar(10)," + "class varchar(10)," + "lvl int,"
				+ "hp int," + "damage int," + "strength int," + "agility int," + "intellect int," + "stamina int,"
				+ "guildId int," + "playerId int," + "equipmentId int)" + ")";
	}

	@Override
	protected String tableName() {
		return "character";
	}

	protected String insertSql() {
		return "INSERT INTO character(name, faction, race, class, lvl, hp, damage, strength, agility, intellect, stamina, guildId, playerId, equipmentId) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE character SET (name, faction, race, class, lvl, hp, damage, strength, agility, intellect, stamina, guildId, playerId, equipmentId)=(?,?,?,?,?,?,?,?,?,?,?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setUpdate(Character entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setObject(2, entity.getFaction());
		insert.setObject(3, entity.getRace());
		insert.setObject(4, entity.getClass());
		insert.setInt(5, entity.getLvl());
		insert.setInt(6, entity.getHp());
		insert.setInt(7, entity.getDamage());
		insert.setInt(8, entity.getStrength());
		insert.setInt(9, entity.getAgility());
		insert.setInt(10, entity.getIntellect());
		insert.setInt(11, entity.getStamina());
		insert.setObject(12, entity.getGuildId());
		insert.setObject(13, entity.getPlayerId());
		insert.setObject(14, entity.getEquipmentId());
	}

	@Override
	protected void setInsert(Character entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setObject(2, entity.getFaction());
		update.setObject(3, entity.getRace());
		update.setObject(4, entity.getClass());
		update.setInt(5, entity.getLvl());
		update.setInt(6, entity.getHp());
		update.setInt(7, entity.getDamage());
		update.setInt(8, entity.getStrength());
		update.setInt(9, entity.getAgility());
		update.setInt(10, entity.getIntellect());
		update.setInt(11, entity.getStamina());
		update.setObject(12, entity.getGuildId());
		update.setObject(13, entity.getPlayerId());
		update.setObject(14, entity.getEquipmentId());
	}

}