package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IEquipmentRepository;
import dao.uow.IUnitOfWork;
import domain.model.Equipment;;

public class EquipmentRepository extends RepositoryBase<Equipment> implements IEquipmentRepository {

	public EquipmentRepository(Connection connection, IMapResultSetIntoEntity<Equipment> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE equipment(" + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "head varchar(30)," + ")";
	}

	@Override
	protected String tableName() {
		return "equipment";
	}

	protected String insertSql() {
		return "INSERT INTO equipment(name, stat1, value1, stat2, value2, stat3, value3) VALUES (?,?,?,?,?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE equipment SET (name, stat1, value1, stat2, value2, stat3, value3)=(?,?,?,?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setUpdate(Equipment entity) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void setInsert(Equipment entity) throws SQLException {
		// TODO Auto-generated method stub
		
	}

}