package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.Guild;

public class GuildRepository extends RepositoryBase<Guild> {

	public GuildRepository(Connection connection, IMapResultSetIntoEntity<Guild> mapper) {
		super(connection,mapper);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE guild("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "faction varchar(10)," + ")";
	}

	@Override
	protected String tableName() {
		return "guild";
	}

	protected String insertSql() {
		return "INSERT INTO guild(name, faction) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE guild SET (name, faction)=(?,?) WHERE id=?";
	}

	@Override
	protected void setInsert(Guild entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getFaction());
	}
	
	@Override
	protected void setUpdate(Guild entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getFaction());
	}

}