package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.Item;

public class ItemRepository extends RepositoryBase<Item> {

	public ItemRepository(Connection connection, IMapResultSetIntoEntity<Item> mapper) {
		super(connection,mapper);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE item("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "stat1 varchar(30)," + "stat2 varchar(30)," + "stat3 varchar(30)," + ")";
	}

	@Override
	protected String tableName() {
		return "item";
	}

	protected String insertSql() {
		return "INSERT INTO item(name, stat1, stat2, stat3) VALUES (?,?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE item SET (name, stat1, stat2, stat3)=(?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setInsert(Item entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getStat1());
		insert.setString(3, entity.getStat2());
		insert.setString(4, entity.getStat3());
	}
	
	@Override
	protected void setUpdate(Item entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getStat1());
		update.setString(3, entity.getStat2());
		update.setString(4, entity.getStat3());
	}

}