package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IItemRepository;
import dao.uow.IUnitOfWork;
import domain.model.Item;

public class ItemRepository extends RepositoryBase<Item> implements IItemRepository {

	public ItemRepository(Connection connection, IMapResultSetIntoEntity<Item> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE item(" + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "stat1 varchar(30)," + "value1 int," + "stat2 varchar(30)," + "value2 int,"
				+ "stat3 varchar(30)," + "value3 int," + ")";
	}

	@Override
	protected String tableName() {
		return "item";
	}

	protected String insertSql() {
		return "INSERT INTO item(name, stat1, value1, stat2, value2, stat3, value3) VALUES (?,?,?,?,?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE item SET (name, stat1, value1, stat2, value2, stat3, value3)=(?,?,?,?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setInsert(Item entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getStat1());
		insert.setInt(3, entity.getValue1());
		insert.setString(4, entity.getStat2());
		insert.setInt(5, entity.getValue2());
		insert.setString(6, entity.getStat3());
		insert.setInt(7, entity.getValue3());
	}

	@Override
	protected void setUpdate(Item entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getStat1());
		update.setInt(3, entity.getValue1());
		update.setString(4, entity.getStat2());
		update.setInt(5, entity.getValue2());
		update.setString(6, entity.getStat3());
		update.setInt(7, entity.getValue3());
	}

}