package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IItemRepository;
import dao.uow.IUnitOfWork;
import domain.model.Item;

public class ItemRepository extends RepositoryBase<Item> implements IItemRepository {

    private PreparedStatement getName;
    private PreparedStatement getStat;
	
	public ItemRepository(Connection connection, IMapResultSetIntoEntity<Item> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
		try {
            getName = connection.prepareStatement(getNameSql());
            getStat = connection.prepareStatement(getStatSql());
        } catch (SQLException e) {
            e.printStackTrace();
        }
		
	}

	private String getStatSql() {
		return "SELECT * FROM item WHERE stat1=? OR stat2=? OR stat3=?";
	}

	private String getNameSql() {
		return "SELECT * FROM item WHERE name=?";
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE item(" + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(50)," + "stat1 varchar(30)," + "value1 int," + "stat2 varchar(30)," + "value2 int,"
				+ "stat3 varchar(30)," + "value3 int" + ")";
	}

	@Override
	protected String tableName() {
		return "item";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO item(name, stat1, value1, stat2, value2, stat3, value3) VALUES (?,?,?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE item SET (name, stat1, value1, stat2, value2, stat3, value3)=(?,?,?,?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setInsert(Item entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getStat1());
		insert.setInt(3, entity.getValue1());
		insert.setString(4, entity.getStat2());
		insert.setInt(5, entity.getValue2());
		insert.setString(6, entity.getStat3());
		insert.setInt(7, entity.getValue3());
	}

	@Override
	protected void setUpdate(Item entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getStat1());
		update.setInt(3, entity.getValue1());
		update.setString(4, entity.getStat2());
		update.setInt(5, entity.getValue2());
		update.setString(6, entity.getStat3());
		update.setInt(7, entity.getValue3());
	}

	public List<Item> withName(String name) {
        List<Item> items = new ArrayList<Item>();
        try{
            getName.setString(1, name);
            ResultSet resultSet = getName.executeQuery();
            while(resultSet.next()){
            	items.add(mapper.map(resultSet));
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        return items;
	}

	public List<Item> withStat(String stat) {
        List<Item> items = new ArrayList<Item>();
        try{
            getStat.setString(1, stat);
            getStat.setString(2, stat);
            getStat.setString(3, stat);
            ResultSet resultSet = getName.executeQuery();
            while(resultSet.next()){
            	items.add(mapper.map(resultSet));
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        return items;
	}

}