package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.Player;

public class PlayerRepository extends RepositoryBase<Player> {
	
	public PlayerRepository(Connection connection, IMapResultSetIntoEntity<Player> mapper) {
		super(connection,mapper);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE player("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50),"
				+ "email varchar(50)," + "country varchar(20)" + ")";
	}

	@Override
	protected String tableName() {
		return "player";
	}

	protected String insertSql() {
		return "INSERT INTO player(name, surname, email, country) VALUES (?,?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE player SET (name, surname, email, country)=(?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setInsert(Player entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
		insert.setString(3, entity.getEmail());
		insert.setString(4, entity.getCounty());
	}
	
	@Override
	protected void setUpdate(Player entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setString(3, entity.getEmail());
		update.setString(4, entity.getCounty());
	}

}