package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IPlayerRepository;
import dao.uow.IUnitOfWork;
import domain.model.Player;

public class PlayerRepository extends RepositoryBase<Player> implements IPlayerRepository {
	
	public PlayerRepository(Connection connection, IMapResultSetIntoEntity<Player> mapper, IUnitOfWork uow) {
		super(connection,mapper,uow);
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE player("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "login varchar(20)," + "password varchar(50),"
				+ "name varchar(20)," + "surname varchar(50),"
				+ "email varchar(50)," + "country varchar(20)" + ")";
	}

	@Override
	protected String tableName() {
		return "player";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO player(login, password, name, surname, email, country) VALUES (?,?,?,?,?,?)";
	}
	
	@Override
	protected String updateSql() {
		return "UPDATE player SET (login, password, name, surname, email, country)=(?,?,?,?,?,?) WHERE id=?";
	}

	@Override
	protected void setInsert(Player entity) throws SQLException {
		insert.setString(1, entity.getLogin());
		insert.setString(2, entity.getPassword());
		insert.setString(3, entity.getName());
		insert.setString(4, entity.getSurname());
		insert.setString(5, entity.getEmail());
		insert.setString(6, entity.getCounty());
	}
	
	@Override
	protected void setUpdate(Player entity) throws SQLException {
		update.setString(1, entity.getLogin());
		update.setString(2, entity.getPassword());
		update.setString(3, entity.getName());
		update.setString(4, entity.getSurname());
		update.setString(5, entity.getEmail());
		update.setString(6, entity.getCounty());
	}

}